/* eslint-disable react/react-in-jsx-scope */
import CampNotiActionCell from 'src/components/DataGridCustomCells/CampNotiActionCell';

export const getcampaignNotiCols = (getDasList, daRes, pageRoles) => [
  {
    field: 'campaignName',
    headerName: 'Campaign Name',
    flex: 1,
    minWidth: 120,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'startDate',
    headerName: 'Start Date',
    flex: 1,
    minWidth: 70,
    // Width: 80,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: true,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'finishDate',
    headerName: 'Finish Date',
    flex: 1,
    minWidth: 70,
    // Width: 80,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: true,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'networkName',
    headerName: 'Network Name',
    flex: 1,
    minWidth: 140,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'totalMessage',
    headerName: 'Total Message',
    flex: 1,
    minWidth: 140,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'totalSent',
    headerName: 'Total Sent',
    flex: 1,
    minWidth: 140,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'totalFailed',
    headerName: 'Total Failed',
    flex: 1,
    minWidth: 140,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    headerClassName: 'custom-header-data-grid',
  },
  {
    field: 'totalUnDelivered',
    headerName: 'Total UnDelivered',
    flex: 1,
    minWidth: 140,
    editable: false,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    headerClassName: 'custom-header-data-grid',
  },
 
];
