/* eslint-disable react/react-in-jsx-scope */
import DADSspsListCell from 'src/components/DataGridCustomCells/DADSspsListCell';

export const getDADspsListCols = (fetchDspList, dspsList, pageRoles) => [
  {
    field: 'firstName',
    headerName: 'Name',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    minWidth: 95,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
  },
  {
    field: 'contact',
    headerName: 'Contact',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    minWidth: 110,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
  },
  {
    field: 'country',
    headerName: 'Country',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    minWidth: 80,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
  },
  {
    field: 'state',
    headerName: 'State',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    minWidth: 70,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    hide: true,
  },
  {
    field: 'lastUpdatedAt',
    headerName: 'lastUpdatedAt',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    minWidth: 70,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
    hide: true,
  },
  {
    field: 'businessType',
    headerName: 'Business Type',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    minWidth: 130,
    filterable: true,
    sortable: true,
    disableColumnMenu: false,
  },
  {
    field: 'partners',
    headerName: 'Partners',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    maxWidth: 80,
    filterable: true,
    align: 'center',
   // headerAlign: 'center',
    sortable: true,
    disableColumnMenu: false,
  },
  {
    field: 'fleet',
    headerName: 'Fleet',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    editable: false,
    maxWidth: 60,
    filterable: true,
    align: 'center',
  //  headerAlign: 'center',
    sortable: true,
    disableColumnMenu: false,
  },
  {
    field: 'status',
    headerName: 'Action',
    headerClassName: 'custom-header-data-grid',
    flex: 1,
    minWidth: 160,
    editable: false,
    filterable: false,
    sortable: true,
    disableColumnMenu: true,
    renderCell: (params) => (
      <DADSspsListCell
        value={params}
        fetchDspList={fetchDspList}
        user={dspsList.filter((item) => item.id === params.row.id)}
        canDelete={pageRoles.canDelete}
        canUpdate={pageRoles.canUpdate}
      />
    ),
  },
];
