/* eslint-disable react/react-in-jsx-scope */
// userFormConfig.js

import {
  cilUser,
  cilEnvelopeClosed,
  cilScreenSmartphone,
  cilFlagAlt,
  cilInfo,
  cilCalendar
} from '@coreui/icons';
import { CFormCheck } from '@coreui/react';
import moment from 'moment';
import CustomInput from 'src/components/InputsComponent/CustomInput';
import CustomSelectInput from 'src/components/InputsComponent/CustomSelectInput';
import CustomDatePicker from 'src/components/UI/DatePicker';
import ImagePicker from 'src/components/UI/ImagePicker';
import globalutil from 'src/util/globalutil';

export const getCampaignAddConfig = (
  daUserData,
  handleUserInput,
  TermsModal,
  emailMessage,
  onBlur,
) => [
 
  {
    component: CustomInput,
    label: 'Title',
    value: daUserData.name,
    onChange: handleUserInput,
    icon: cilUser,
    type: 'text',
    id: 'name',
    name: 'name',
    placeholder: 'Title / short description',
    className: 'form-control item',
    isRequired: true,
    maxLength: 20,
    // pattern: '.*[A-Z].*',
    message: 'Enter Title',
    autoFocus: true,
  },
  {
    component: CustomInput,
    label: '# Tag',
    value: daUserData.tag,
    onChange: handleUserInput,
    icon: cilUser,
    type: 'text',
    id: 'tag',
    name: 'tag',
    placeholder: '#tag',
    className: 'form-control item',
    isRequired: false,
    // maxLength: 10,
    // pattern: '.*[A-Z].*',
    message: 'Enter #Tag',
  },
  {
    component: CustomInput,
    label: 'Video Attachment',
    value: daUserData.attachment,
    onChange: handleUserInput,
    icon: cilEnvelopeClosed,
    type: 'file',
    id: 'attachment',
    name: 'attachment',
    className: 'form-control item',
    isRequired: false,
  },
    {
      component: CustomSelectInput,
      label: 'Status',
      icon: cilInfo,
      id: 'status',
      options: globalutil.statuses(),
      className: 'form-control item form-select',
      value: daUserData.status,
      name: 'status',
      onChange: (e) => handleUserInput(e),
      isRequired: false,
      disableOption: 'Select Status',
      message: 'Please select user status',
    },
 
    {
      component: CustomInput,
      label: 'Image Attachment',
      value: daUserData.imgattachment,
      onChange: handleUserInput,
      icon: cilEnvelopeClosed,
      type: 'file',
      id: 'imgattachment',
      name: 'imgattachment',
      className: 'form-control item',
      isRequired: false,
    },
    {
      component: CustomInput,
      label: 'Pdf Attachment',
      value: daUserData.pdfattachment,
      onChange: handleUserInput,
      icon: cilEnvelopeClosed,
      type: 'file',
      id: 'pdfattachment',
      name: 'pdfattachment',
      className: 'form-control item',
      isRequired: false,
    },
    {
      component: CustomDatePicker,
      label: 'Campaign Start Date',
      value: daUserData.startDate,
      onChange: handleUserInput,
      icon: cilCalendar,
      id: 'startDate',
      name: 'startDate',
      className: 'form-control item',
      isRequired: false,
    },
    {
      component: CustomDatePicker,
      label: 'Campaign End Date',
      value: daUserData.endDate,
      onChange: handleUserInput,
      icon: cilCalendar,
      id: 'endDate',
      name: 'endDate',
      className: 'form-control item',
      isRequired: false,
    },
    {
      component: CFormCheck,
      label: 'Generate Auto Leads',
      value: daUserData.autoLeads,
     // onChange: handleUserInput,
      icon: cilCalendar,
      id: 'autoLeads',
      name: 'autoLeads',
      className: 'mt-2',
      isRequired: false,
    },
 
];
export const getInitialDspData = (user) => ({
  id: 0,
  logoPath: '',
  name: '',
  tradeName: '',
  contact: '',
  email: '',
  isWhatsappAsso: false,
  country: '',
  stateId: '',
  status: 1,
  webAddress: '',
  surfaceAddress: '',
  businessTypeId: '',
  isTermsAccepted: false,
  createdBy: user.userId,
  lastUpdatedBy: user.userId,
  createdAt: moment().utc().format(),
});
